from typing import Protocol

from accelerator.domain import Capabilities, ProbeResult, ProxyNode


class CoreAdapter(Protocol):
    capabilities: Capabilities

    async def start(self, config: dict) -> None: ...
    async def stop(self) -> None: ...
    async def restart(self, config: dict) -> None: ...
    async def health_check(self) -> bool: ...
    async def apply_config(self, config: dict) -> None: ...
    async def get_status(self) -> str: ...
    async def get_traffic(self) -> dict[str, int]: ...
    async def get_logs(self) -> list[dict[str, str]]: ...
    async def test_node(self, node: ProxyNode) -> ProbeResult: ...
